### ISSUE TITLE
stdin breaks after opening a file

### ISSUE THREAD

**Issue by DarkElvenAngel** [Memotech-Bill/pico-filesystem#6]
I've added a test case to my [fork](https://github.com/DarkElvenAngel/pico-filesystem) that will test reading from `stdin` before and after the write read tests.

In my test reading from `stdin` will lock up after any file is opened.

This is a follow up to your [RPI forum posts]( https://forums.raspberrypi.com/viewtopic.php?p=2160633&sid=6785bc3aec0613e32aed8e06f61dfaf6#p2160633) that requested me to open an issue.

**Comment by DarkElvenAngel** [comment]
I've done some digging into this and added some printf lines to ` _read` and `tty_read`

before a file is opened I can see that `_read` and `_tty_read` are called as normal however after a file is opened only `_read` is called and  `_tty_read` isn't.  I'll update here as I narrow in on the issue.

Note certain when it happens but the address to `_tty_read` is corrupted

```
[READ 0 0x100376E9][READ TTY]
[READ 0 0x000000EF]

```

**Comment by DarkElvenAngel** [comment]
I've found the mistake you aren't allocating enough memory in [pfs_base.c](https://github.com/Memotech-Bill/pico-filesystem/blob/ea63db178216a86afbb73fa9a9787d94d1b7f4ef/pfs/pfs_base.c#L206) Line 206 this is creating a buffer overrun.  

`    struct pfs_file ** fi2 = (struct pfs_file **) realloc (files, nh);`

Should be something more in like this.

`    struct pfs_file ** fi2 = (struct pfs_file **) pfs_realloc (files, sizeof(struct pfs_file) * nh);`

**Comment by Memotech-Bill** [comment]
Thank you for saving me the trouble of tracking down the fault.

The reallocation should actually be nh times size of a pointer, not nh times the size of the pfs_fine structure:

````
struct pfs_file ** fi2 = (struct pfs_file **) realloc (files, nh * sizeof (pfs_file *));
````

I have committed this change.

**Comment by DarkElvenAngel** [comment]
You need to make that 

```C
struct pfs_file ** fi2 = (struct pfs_file **) realloc (files, nh * sizeof (struct pfs_file *));
```

**Comment by Memotech-Bill** [comment]
Quite right, thanks.

Too busy with other things at the moment.

**Comment by DarkElvenAngel** [comment]
No problem seems to be working now.
