### ISSUE TITLE
Question: How do you access the lfs struct

### ISSUE THREAD

**Issue by DarkElvenAngel** [Memotech-Bill/pico-filesystem#9]
So I want to implement a method to get the disk free on the Littlefs however I can't seem to get the reference to the lfs_t that is required for low level access.

I'm looking to port this code over so it will work.

```c
  int res = (int)lfs_fs_size (&lfs);
  if (res >= 0) 
    {
    *used = (uint32_t)res * INTERFACE_STORAGE_BLOCK_SIZE;
    *total = INTERFACE_STORAGE_BLOCK_SIZE * INTERFACE_STORAGE_BLOCK_COUNT;
    }
```
I've tried to get the reference from the return of `pfs_ffs_create(&cfg);`  any ideas?  There may be other calls this could be useful for?

**Comment by Memotech-Bill** [comment]
````
struct ffs_pfs
    {
    const struct pfs_v_pfs *    entry;
    lfs_t                       base;
    struct lfs_config           cfg;
    };

struct pfs_pfs *pfs = pfs_ffs_create (&cfg);

lfs_t * plfs = &((struct ffs_pfs *) pfs)->base;
````

**Comment by DarkElvenAngel** [comment]
Thank you that works.
